### ISSUE TITLE
Fix gcc/perl issues == re-instate entrypoint in Docker image?

### ISSUE THREAD

**Issue by mbargull** [bioconda/bioconda-utils#260] opened 2018-01-29 18:57 UTC
I took some time so get on track about the `perl`/`gcc` issues (https://github.com/conda-forge/perl-feedstock/pull/12, https://github.com/conda-forge/perl-feedstock/issues/16) with `defaults::gcc` and the `gcc` in `condaforge/linux-anvil`.
(@jerowe: Now I understand what you meant in https://github.com/bioconda/bioconda-recipes/pull/7410#issuecomment-361273181 ! 😄)

Now I'm (nearly) certain that https://github.com/bioconda/bioconda-utils/commit/2bfbbbf137513b51e2ae9dc8a33257c97c064fe1 could have caused the recent issues with `perl` recipes (https://github.com/bioconda/bioconda-recipes/issues/7415, https://github.com/bioconda/bioconda-recipes/pull/7408, ...).
It looks like it is crucial to use the image's entrypoint as it enables the `devtoolset-2` (put on `PATH`, etc., I assume), see: https://github.com/conda-forge/docker-images/blob/dae46482a0b87f4bc2ff7ad519dc9ecd76949be9/linux-anvil/entrypoint_source#L8.

@johanneskoester: I haven't yet looked at want you meant with "leads to an endless chown" in your commit message, so I'm only opening this issues, but have no fix, yet.

**Comment by jerowe** [comment] 2018-01-30 05:33
@mbargull , glad its clearer. Once you responded I realized my saying the toolchain was sourced was a very ambiguous statement. ;-)

If sourcing the toolchain is a problem we could always just preface the PATH? 

`export PATH=/opt/rh/devtoolset-2/root/usr/bin/:$PATH`

I have the feeling that if we don't add this in we are breaking binary compatibility with conda-forge. Specifically with perl things, but since conda-forge is a higher channel priority than defaults anything that is pulled in from there that is compiled will also be broken. I believe this included scientific python packages like numpy, scipy, matplotlib, but I haven't dug too deep into those.

**Comment by mbargull** [comment] 2018-01-30 05:52
Well, I hope that this "leads to an endless chown" Johannes observed might've only been a coincidence. If we could just re-use the entrypoint, that would certainly be the easiest way to retain compatibility.

**Comment by mbargull** [comment] 2018-01-30 20:53
@johanneskoester: What were the exact problems that entrypoint caused? Could/should we just try to reinstate it and see what happens?

**Comment by johanneskoester** [comment] 2018-01-31 08:53
So they do a chown on the miniconda folder. With my changes to the image (installing bioconda-utils), miniconda folder is so big that this chown takes ages. I don't know how long it took before, but it is certainly still a waste of time. We can undo my changes though. I can create a separate image for the local circleci builds.

**Comment by johanneskoester** [comment] 2018-01-31 10:17
I just had a look, and to me, that entrypoint is simply broken. The chown already takes 8 minutes on their raw image without any of our modifications (on my laptop, probably due to the meltdown patches). This means at least that people who locally build with bioconda-utils or `circleci build` would suffer from that wait time. Moreover, we would waste a lot of CI time if it is an issue there as well.

**Comment by johanneskoester** [comment] 2018-01-31 10:18
xref: conda-forge/docker-images#63

**Comment by johanneskoester** [comment] 2018-01-31 10:23
@daler could you help us here? The conda-forge guys use a chown -R on the conda installation to make it accessible to their docker container user, which is configured to have the same user id as the host user. I remember that you also build a solution for this volume permission problem into bioconda-utils, but that did not involve such a chown, right?

**Comment by johanneskoester** [comment] 2018-01-31 10:24
@jerowe, the gcc from devtoolset-2 available in the conda forge image is 4.8.2 isn't it? If I am not mistaken, that is even older than the one from the defaults channel.

**Comment by mbargull** [comment] 2018-01-31 10:27
Acc. to https://github.com/conda-forge/perl-feedstock/pull/12#issuecomment-282003891 that `gcc` is a patched `4.8.2` (contains backported features).

**Comment by mbargull** [comment] 2018-01-31 10:30
How crucial is that `chown -R`? If it's usually not that important, could just copy&paste their entrypoint and just leave that command out, as a temporary solution?

**Comment by johanneskoester** [comment] 2018-01-31 10:36
The only thing we would need from the entry point is the activation of devtoolset-2: `. scl_source enable devtoolset-2`. The rest is related to their conda user, and would only work together with the chown. But since we don't need the conda user, we can simply skip it and have our own entrypoint containing only the activation of the devtoolset-2 stuff. @mbargull could you take care of that?

**Comment by mbargull** [comment] 2018-01-31 10:43
Will do, thanks for clarifying!

**Comment by daler** [comment] 2018-01-31 14:36
@johanneskoester I'll take a look this afternoon to see if we can avoid a chown -R by controlling user IDs (this would be orthogonal to what @mbargull ends up doing, so I don't slow you down).

**Comment by mbargull** [comment] 2018-01-31 14:50
@daler, I'm pretty much a newbie on Docker, so I did a quick search earlier which came up with:
* https://github.com/tootsuite/mastodon/issues/3194
* https://denibertovic.com/posts/handling-permissions-with-docker-volumes/
* https://github.com/jupyter/docker-stacks/pull/84/files

. Maybe something of that is helpful to you.

**Comment by daler** [comment] 2018-01-31 22:39
Folowing up . . . quoting from https://denibertovic.com/posts/handling-permissions-with-docker-volumes/:

> Docker provides a -u flag with its run command to dynamically switch to a specified UID during container start. So we can write something like this:

> ```
> deni@kanta:~$ docker run -it -u `id -u $USER` debian:jessie /bin/bash
> I have no name!@dcb415bad433:/$ id
> uid=1000 gid=0(root) groups=0(root)
> ```
>
> This approach, while dynamic in the sense that the UID is specified at runtime, has 2 drawbacks:
>
> 1. The GID (group id) of the user is still 0 (root)
> 2.  The UID 1000 is not present in the container's /etc/passwd file.
>
> While no. 1. is definitely problematic for obvious reasons no. 2. is where we hit a wall. Now while the Linux Filesystem doesn't really care about user names, rather just UID's, some applications will refuse to start if the user is not present in /etc/passwd.

When originally writing `bioconda_utils.docker_utils` I did not see any errors caused by the user not being in `/etc/passwd`, at least with our limited use-case of just running conda. So the `-u` option was the simplest option. #262 maintains that strategy -- and that PR looks great.

**Comment by epruesse** [comment] 2019-03-14 04:34
The issue must have gone away in the past year. Closing.

**Closed by epruesse** 2019-03-14 04:34 UTC
